language: python

python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - coverage run --source=jobs --omit=../*tests*,../*migrations*,../*init* manage.py test

after_success:
  coveralls

