language: python

python:
  - "2.7"
  - "3.4"

env: SECRET_KEY='secret' AWS_ACCESS_KEY_ID='AWS_KEY_ID' AWS_SECRET_ACCESS_KEY='AWS_SECRET_KEY'

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - coverage run --source=jobs --omit=../*tests*,../*migrations*,../*init* manage.py test

after_success:
    - coveralls
